const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.NinePatch,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.TextBox,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Sin,
		C3.Plugins.Dictionary,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Text.Acts.SetWidth,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Text.Exps.BBoxRight,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Exps.FaceName,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Acts.SetInstanceVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.TextBox.Cnds.IsFocused,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.DrawingCanvas.Acts.PasteObject
	];
};
self.C3_JsPropNameTable = [
	{BGSolidColor: 0},
	{AksaraFrame: 0},
	{AppTitle: 0},
	{StartButton: 0},
	{Touch: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{Audio: 0},
	{HowButton: 0},
	{InfoButton: 0},
	{AudioButton: 0},
	{CloseButton: 0},
	{Pin: 0},
	{ButtonShadow: 0},
	{LogoBG1: 0},
	{LogoBG2: 0},
	{PageTitle: 0},
	{MargiangButton: 0},
	{SargahButton: 0},
	{KuisButton: 0},
	{PageBackButton: 0},
	{SasobiahanButton: 0},
	{NgawigunayangButton: 0},
	{HomeButton: 0},
	{SasobiahanAksaraWreastraButton: 0},
	{SasobiahanGempelanGantunganButton: 0},
	{SasobiahanPenggaeSuaraButton: 0},
	{SasobiahanAngkaButton: 0},
	{NgawigunayangAksaraWreastraButton: 0},
	{NgawigunayangGempelanGantunganButton: 0},
	{NgawigunayangPenggaeSuaraButton: 0},
	{NgawigunayangAngkaButton: 0},
	{MargiangAksaraWreastraButton: 0},
	{MargiangGempelanGantunganButton: 0},
	{MargiangPenggaeSuaraAngkaButton: 0},
	{ID: 0},
	{Prefix: 0},
	{GempelanGantunganSasobiahanButton: 0},
	{PenggaeSuaraSasobiahanButton: 0},
	{AngkaSasobiahanButton: 0},
	{PreFix: 0},
	{AksaraWreastraSasobiahanButton: 0},
	{AksaraWreastraMargiangButton: 0},
	{GempelanGantunganMargiangButton: 0},
	{PenggaeSuaraAngkaMargiangButton: 0},
	{NextRedButton: 0},
	{BGRounded: 0},
	{BaseMateri: 0},
	{Padding: 0},
	{vScrollContent: 0},
	{StartY: 0},
	{Active: 0},
	{Add: 0},
	{Direction: 0},
	{StartPos: 0},
	{vScrollManager: 0},
	{vScrollPanel: 0},
	{ContentCount: 0},
	{ContentHeight: 0},
	{DistanceBetween: 0},
	{StartEndIndent: 0},
	{StepMouse: 0},
	{NSizeOfList: 0},
	{NOffset: 0},
	{NStartY: 0},
	{vScroll: 0},
	{MateriMask: 0},
	{QuestionText: 0},
	{AJAX: 0},
	{ArrayMultipleQuestionID: 0},
	{PanelBlueYellowOutline: 0},
	{UIText: 0},
	{QuestionPuzzlePanel: 0},
	{AnswerLetter: 0},
	{True: 0},
	{AnswerText: 0},
	{Used: 0},
	{Clickable: 0},
	{Text: 0},
	{AnswerButton: 0},
	{DropArea: 0},
	{PuzzleQuestion: 0},
	{InitX: 0},
	{InitY: 0},
	{Placed: 0},
	{DraggableObject: 0},
	{DragPos: 0},
	{BaosButton: 0},
	{ArrayPuzzleID: 0},
	{Browser: 0},
	{RetryButton: 0},
	{QuizMenuButton: 0},
	{Tween: 0},
	{ScoreText: 0},
	{TataCaraPengembang: 0},
	{LinkText: 0},
	{vScrollBar: 0},
	{Cof: 0},
	{Proc: 0},
	{vScrollBarHandle: 0},
	{vScrollUpButton: 0},
	{vScrollDownButton: 0},
	{Mask: 0},
	{PopClose: 0},
	{PopCloseNoButton: 0},
	{PopCloseYesButton: 0},
	{foto: 0},
	{FeedbackQuiz: 0},
	{UserAnswer: 0},
	{CorrectAnswer: 0},
	{TextInput: 0},
	{DrawFrame: 0},
	{DrawCloseButton: 0},
	{DrawResetButton: 0},
	{DrawingCanvas: 0},
	{Ink: 0},
	{CanvasAksaraGuide: 0},
	{BGMascotBack: 0},
	{Sine: 0},
	{BGMascotLeft: 0},
	{BGMascotRight: 0},
	{BGMascotFront: 0},
	{QuizType: 0},
	{ResultQuestion: 0},
	{ResultDictionary: 0},
	{Letter: 0},
	{ResultPilihanGandaAnswerLetter: 0},
	{ResultAnswer: 0},
	{InitFrame: 0},
	{UserFrame: 0},
	{ResultPuzzleUserAnswer: 0},
	{ResultArrow: 0},
	{ResultPuzzleCorrectAnswer: 0},
	{Buttons: 0},
	{BarButtons: 0},
	{GempelanGantunganSasobiahanButtons: 0},
	{PenggaeSuaraSasobiahanButtons: 0},
	{AngkaSasobiahanButtons: 0},
	{AksaraWreastraSasobiahanButtons: 0},
	{AksaraWreastraMargiangButtons: 0},
	{GempelanGantunganMargiangButtons: 0},
	{PenggaeSuaraAngkaMargiangButtons: 0},
	{AnswerTexts: 0},
	{AnswerButtons: 0},
	{DropAreas: 0},
	{DragDrop: 0},
	{DraggableObjects: 0},
	{AnswerLetters: 0},
	{AnswerInputs: 0},
	{MultipleChoicesIndex: 0},
	{PuzzleIndex: 0},
	{BGM: 0},
	{PressPower: 0},
	{LeftCyclePosition: 0},
	{RightCyclePosition: 0},
	{Name: 0},
	{Volume: 0},
	{Tag: 0},
	{PosX: 0},
	{PosY: 0},
	{Width: 0},
	{Height: 0},
	{PosXPosY: 0},
	{WidthHeight: 0},
	{AnimationFrame: 0},
	{MultipleChoiceScore: 0},
	{PuzzlePlaced: 0},
	{PuzzleScore: 0},
	{Correct: 0},
	{PrevLayout: 0},
	{Drawing: 0},
	{oldX: 0},
	{oldY: 0},
	{smoothingSteps: 0}
];

self.InstanceType = {
	BGSolidColor: class extends self.ISpriteInstance {},
	AksaraFrame: class extends self.ISpriteInstance {},
	AppTitle: class extends self.ISpriteInstance {},
	StartButton: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	HowButton: class extends self.ISpriteInstance {},
	InfoButton: class extends self.ISpriteInstance {},
	AudioButton: class extends self.ISpriteInstance {},
	CloseButton: class extends self.ISpriteInstance {},
	ButtonShadow: class extends self.ISpriteInstance {},
	LogoBG1: class extends self.ISpriteInstance {},
	LogoBG2: class extends self.ISpriteInstance {},
	PageTitle: class extends self.ISpriteInstance {},
	MargiangButton: class extends self.ISpriteInstance {},
	SargahButton: class extends self.ISpriteInstance {},
	KuisButton: class extends self.ISpriteInstance {},
	PageBackButton: class extends self.ISpriteInstance {},
	SasobiahanButton: class extends self.ISpriteInstance {},
	NgawigunayangButton: class extends self.ISpriteInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	SasobiahanAksaraWreastraButton: class extends self.ISpriteInstance {},
	SasobiahanGempelanGantunganButton: class extends self.ISpriteInstance {},
	SasobiahanPenggaeSuaraButton: class extends self.ISpriteInstance {},
	SasobiahanAngkaButton: class extends self.ISpriteInstance {},
	NgawigunayangAksaraWreastraButton: class extends self.ISpriteInstance {},
	NgawigunayangGempelanGantunganButton: class extends self.ISpriteInstance {},
	NgawigunayangPenggaeSuaraButton: class extends self.ISpriteInstance {},
	NgawigunayangAngkaButton: class extends self.ISpriteInstance {},
	MargiangAksaraWreastraButton: class extends self.ISpriteInstance {},
	MargiangGempelanGantunganButton: class extends self.ISpriteInstance {},
	MargiangPenggaeSuaraAngkaButton: class extends self.ISpriteInstance {},
	GempelanGantunganSasobiahanButton: class extends self.ISpriteInstance {},
	PenggaeSuaraSasobiahanButton: class extends self.ISpriteInstance {},
	AngkaSasobiahanButton: class extends self.ISpriteInstance {},
	AksaraWreastraSasobiahanButton: class extends self.ISpriteInstance {},
	AksaraWreastraMargiangButton: class extends self.ISpriteInstance {},
	GempelanGantunganMargiangButton: class extends self.ISpriteInstance {},
	PenggaeSuaraAngkaMargiangButton: class extends self.ISpriteInstance {},
	NextRedButton: class extends self.ISpriteInstance {},
	BGRounded: class extends self.ISpriteInstance {},
	BaseMateri: class extends self.ISpriteInstance {},
	vScrollContent: class extends self.ISpriteInstance {},
	vScrollManager: class extends self.ISpriteInstance {},
	vScrollPanel: class extends self.ISpriteInstance {},
	vScroll: class extends self.ISpriteInstance {},
	MateriMask: class extends self.ISpriteInstance {},
	QuestionText: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	ArrayMultipleQuestionID: class extends self.IArrayInstance {},
	PanelBlueYellowOutline: class extends self.IWorldInstance {},
	UIText: class extends self.ITextInstance {},
	QuestionPuzzlePanel: class extends self.ISpriteInstance {},
	AnswerLetter: class extends self.ISpriteInstance {},
	AnswerText: class extends self.ITextInstance {},
	AnswerButton: class extends self.ISpriteInstance {},
	DropArea: class extends self.ISpriteInstance {},
	PuzzleQuestion: class extends self.ITextInstance {},
	DraggableObject: class extends self.ISpriteInstance {},
	DragPos: class extends self.ISpriteInstance {},
	BaosButton: class extends self.ISpriteInstance {},
	ArrayPuzzleID: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	RetryButton: class extends self.ISpriteInstance {},
	QuizMenuButton: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	TataCaraPengembang: class extends self.ISpriteInstance {},
	LinkText: class extends self.ITextInstance {},
	vScrollBar: class extends self.ISpriteInstance {},
	vScrollBarHandle: class extends self.ISpriteInstance {},
	vScrollUpButton: class extends self.ISpriteInstance {},
	vScrollDownButton: class extends self.ISpriteInstance {},
	Mask: class extends self.ISpriteInstance {},
	PopClose: class extends self.ISpriteInstance {},
	PopCloseNoButton: class extends self.ISpriteInstance {},
	PopCloseYesButton: class extends self.ISpriteInstance {},
	foto: class extends self.ISpriteInstance {},
	FeedbackQuiz: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	DrawFrame: class extends self.ISpriteInstance {},
	DrawCloseButton: class extends self.ISpriteInstance {},
	DrawResetButton: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Ink: class extends self.ISpriteInstance {},
	CanvasAksaraGuide: class extends self.ISpriteInstance {},
	BGMascotBack: class extends self.ISpriteInstance {},
	BGMascotLeft: class extends self.ISpriteInstance {},
	BGMascotRight: class extends self.ISpriteInstance {},
	BGMascotFront: class extends self.ISpriteInstance {},
	ResultQuestion: class extends self.ITextInstance {},
	ResultDictionary: class extends self.IDictionaryInstance {},
	ResultPilihanGandaAnswerLetter: class extends self.ISpriteInstance {},
	ResultAnswer: class extends self.ITextInstance {},
	ResultPuzzleUserAnswer: class extends self.ISpriteInstance {},
	ResultArrow: class extends self.ISpriteInstance {},
	ResultPuzzleCorrectAnswer: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	BarButtons: class extends self.ISpriteInstance {},
	GempelanGantunganSasobiahanButtons: class extends self.ISpriteInstance {},
	PenggaeSuaraSasobiahanButtons: class extends self.ISpriteInstance {},
	AngkaSasobiahanButtons: class extends self.ISpriteInstance {},
	AksaraWreastraSasobiahanButtons: class extends self.ISpriteInstance {},
	AksaraWreastraMargiangButtons: class extends self.ISpriteInstance {},
	GempelanGantunganMargiangButtons: class extends self.ISpriteInstance {},
	PenggaeSuaraAngkaMargiangButtons: class extends self.ISpriteInstance {},
	AnswerTexts: class extends self.ITextInstance {},
	AnswerButtons: class extends self.ISpriteInstance {},
	DropAreas: class extends self.ISpriteInstance {},
	DraggableObjects: class extends self.ISpriteInstance {},
	AnswerLetters: class extends self.ISpriteInstance {},
	AnswerInputs: class extends self.ITextInputInstance {}
}